version: '3.8'

services:
  django:
    container_name: django
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/application
    ports:
    - 8001:8000
    environment:
      - DEBG=1
      - SECRET_KEY=0000000000000000000001
      - ALLOWED_HOSTS=localhost,127.0.0.1